#!/bin/bash /etc/rc.common
# procd init script for sing-box

START=99
USE_PROCD=1

start_service() {
	if ! ip route show table 100 | grep -q 'local default dev lo'; then
		# 如果路由表不存在，则添加路由表和规则
		ip route add local default dev lo table 100
		ip rule add fwmark 1 table 100
		# 局域网流量走singBox
		iptables -t mangle -N singBox
		# 本机流量走singBoxSelf
		iptables -t mangle -N singBoxSelf
		# 局域网设备白名单中的ip直连
		while IFS= read -r line; do
			# 检查是否符合IP地址或CIDR格式
			if [[ $line =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}(/([0-9]{1,2}))?$ ]]; then
				# 将符合格式的数据添加到iptables规则中
				iptables -t mangle -A singBox -d "$line" -j RETURN
				iptables -t mangle -A singBoxSelf -d "$line" -j RETURN
			fi
		done </usr/local/etc/singBox/rules/局域网设备白名单.txt
		# 所有非53端口直连
		lanIPS=$(ip -o -f inet addr show |grep lan |awk '/scope global/ {print $4}')
		iptables -t mangle -A singBox -d "$lanIPS" -p tcp ! --dport 53 -j RETURN
        iptables -t mangle -A singBox -d "$lanIPS"  -p udp ! --dport 53 -j RETURN
        iptables -t mangle -A singBoxSelf -d "$lanIPS"  -p tcp ! --dport 53 -j RETURN
        iptables -t mangle -A singBoxSelf -d "$lanIPS"  -p udp ! --dport 53 -j RETURN
        # 其余流量走7894端口透明代理
        iptables -t mangle -A singBox -p tcp -j TPROXY --on-port 7894 --tproxy-mark 1
        iptables -t mangle -A singBox -p udp -j TPROXY --on-port 7894 --tproxy-mark 1
        iptables -t mangle -A singBoxSelf  -j RETURN -m mark --mark 2
        iptables -t mangle -A singBoxSelf -p tcp -j MARK --set-mark 1
        iptables -t mangle -A singBoxSelf -p udp -j MARK --set-mark 1
        iptables -t mangle -A PREROUTING -j singBox
        iptables -t mangle -A OUTPUT -j singBoxSelf
	fi
	
	procd_open_instance
	procd_set_param command /usr/local/bin/sing-box run -D /usr/local/etc/singBox
	procd_set_param respawn
	procd_set_param file /var/run/singBox.pid
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

stop_service() {
	# 删除自定义链中的规则
	iptables -t mangle -F singBox
	iptables -t mangle -F singBoxSelf
	# 删除自定义链
	iptables -t mangle -X singBox
	iptables -t mangle -X singBoxSelf
	# 删除在 PREROUTING 和 OUTPUT 链中添加的规则
	iptables -t mangle -D PREROUTING -j singBox
	iptables -t mangle -D OUTPUT -j singBoxSelf
	# 删除路由表和规则
	ip route del local default dev lo table 100
	ip rule del fwmark 1 table 100
	
	procd_close_instance
}
