#!/bin/sh /etc/rc.common
# procd init script for passwall

START=99
USE_PROCD=1

start_service() {
	logPath=$(cat /usr/local/etc/passwall/config.json | jq '.log.output')
	logPath=$(echo "$logPath" | sed 's/^"//;s/"$//')
	if [ "$logPath" != "null" ]; then
		echo -n "" >$logPath
	fi
	clean_rules 2>/dev/null
	procd_open_instance
	procd_set_param command /usr/local/bin/passwall run -D /usr/local/etc/passwall
	procd_set_param respawn
	procd_set_param file /var/run/passwall.pid
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
	if pgrep passwall > /dev/null; then
		creat_rules 2>/dev/null
	fi
}

stop_service() {
	clean_rules 2>/dev/null
	clean_dnsConfig 2>/dev/null
	procd_close_instance
}

clean_rules() {
	if cat /usr/local/etc/passwall/config.json | jq -e '.inbounds | any(.type == "tproxy")' >/dev/null; then
		rm -f /lib/netifd/ppp-up
		cp /lib/netifd/ppp-up.bak /lib/netifd/ppp-up
		# 清除链中的所有规则
#		iptables -t mangle -F diverIPV4
		iptables -t mangle -F passwallIPV4
		iptables -t mangle -F passwallIPV4MASK
		# 删除链中的规则
#		iptables -t mangle -D PREROUTING -p tcp -m socket -j diverIPV4
		iptables -t mangle -D PREROUTING -j passwallIPV4
		iptables -t mangle -D OUTPUT -j passwallIPV4MASK
		# 删除链
#		iptables -t mangle -X diverIPV4
		iptables -t mangle -X passwallIPV4
		iptables -t mangle -X passwallIPV4MASK
		# 删除路由规则
		ip rule del fwmark 1 table 100
		ip route del local default dev lo table 100
		if command -v ip6tables >/dev/null 2>&1; then
			sed -i '/\/etc\/init.d\/passwall restart/d' /lib/netifd/ppp6-up
			# 清除链中的所有规则
#			ip6tables -t mangle -F diverIPV6
			ip6tables -t mangle -F passwallIPV6
			ip6tables -t mangle -F passwallIPV6MASK
			# 删除链中的规则
#			ip6tables -t mangle -D PREROUTING -p tcp -m socket -j diverIPV6
			ip6tables -t mangle -D PREROUTING -j passwallIPV6
			ip6tables -t mangle -D OUTPUT -j passwallIPV6MASK
			# 删除链
#			ip6tables -t mangle -X diverIPV6
			ip6tables -t mangle -X passwallIPV6
			ip6tables -t mangle -X passwallIPV6MASK
			# 删除路由规则
			ip -6 route del local default dev lo table 106
			ip -6 rule del fwmark 1 table 106
		fi
	elif cat /usr/local/etc/passwall/config.json | jq -e '.inbounds | any(.type == "tun")' >/dev/null; then
		rm -f /etc/config/network
		cp /etc/config/network.bak /etc/config/network
		rm -f /etc/config/firewall
		cp /etc/config/firewall.bak /etc/config/firewall
		# 删除iptables规则
		iptables -D FORWARD -o tun+ -j ACCEPT
	else
		exit 1
	fi
}

clean_dnsConfig() {
	# 恢复dns配置
	dnsPort=$(cat /usr/local/etc/passwall/config.json | jq -r '.inbounds[] | select(.type == "direct") | .listen_port')
	dnsConfig=$(uci get dhcp.@dnsmasq[0].server 2>/dev/null)
	if [ $? -eq 0 ] && [ "$dnsConfig" == "127.0.0.1#$dnsPort" ]; then
		uci delete dhcp.@dnsmasq[0].server
		if [ -f /usr/local/etc/passwall/dnsConfig.tmp ]; then
			dnsConfig=$(cat /usr/local/etc/passwall/dnsConfig.tmp)
			uci add_list dhcp.@dnsmasq[0].server=$dnsConfig
			rm -f /usr/local/etc/passwall/dnsConfig.tmp
		fi
		uci commit dhcp
		/etc/init.d/dnsmasq restart
	fi
}

creat_rules() {
	if cat /usr/local/etc/passwall/config.json | jq -e '.inbounds | any(.type == "tproxy")' >/dev/null; then
		rm -f /lib/netifd/ppp-up.bak
		cp /lib/netifd/ppp-up /lib/netifd/ppp-up.bak
		echo "sleep 1" >> /lib/netifd/ppp-up
		echo "/etc/init.d/passwall restart" >> /lib/netifd/ppp-up
		# 获取透明代理端口
		tproxyPort=$(cat /usr/local/etc/passwall/config.json | jq -r '.inbounds[] | select(.type == "tproxy") | .listen_port')
		proxyPorts=$(cat /usr/local/etc/passwall/config.json | jq -r '.inbounds[] | select(.type != "direct") | select(.type != "tproxy") | .listen_port')
		# 获取代理流量标志
		passwallMark=$(cat /usr/local/etc/passwall/config.json | grep mark | head -n 1 | cut -d \: -f2 | sed 's/,//g' | sed 's/^ *//;s/ *$//')
		# 获取FakeIP网段
		fakeIPV4=$(cat /usr/local/etc/passwall/config.json | jq -r '.dns | .fakeip | .inet4_range')
		fakeIPV6=$(cat /usr/local/etc/passwall/config.json | jq -r '.dns | .fakeip | .inet6_range')
		# 获取本机IPV4网段	
		localIPV4=$(ip -o -f inet addr show | awk '/scope/ {print $4}')
		lanIPV4=$(ip -o -f inet addr show | grep "scope global br-lan" | awk '/scope/ {print $4}')
		publicIPV4=$(ip -o -f inet addr show | grep -v "scope host lo" | grep -v "scope global br-lan" | grep -v "scope global docker" | awk '/scope/ {print $4}')

		# 新建路由表
		ip route add local default dev lo table 100
		ip rule add fwmark 1 table 100 priority 1024
		# 局域网设置
		iptables -t mangle -N passwallIPV4
		# 放行代理端口
		if [ -n "$proxyPorts" ]; then
			for port in $proxyPorts; do
				port=$(echo "$port" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
				iptables -t mangle -A passwallIPV4 -p tcp --dport $port -j RETURN
				iptables -t mangle -A passwallIPV4 -p udp --dport $port -j RETURN
			done
		fi
		# 目标为本机IPV4网段的流量不走代理
		lanIP=$(echo $lanIPV4 | cut -d'/' -f1)
		iptables -t mangle -A passwallIPV4 -d $lanIP -j RETURN

		for ipv4 in $localIPV4; do
			if [ $ipv4 == $lanIPV4 ]; then
				# 判断是否自定义了dns接口
				if cat /usr/local/etc/passwall/config.json | jq -e '.inbounds | any(.type == "direct")' >/dev/null; then
					dnsPort=$(cat /usr/local/etc/passwall/config.json | jq -r '.inbounds[] | select(.type == "direct") | .listen_port')
					dnsConfig=$(uci get dhcp.@dnsmasq[0].server 2>/dev/null)
					if [ $? -eq 0 ] && [ "$dnsConfig" != "127.0.0.1#$dnsPort" ]; then
						if [ ! -d "/usr/local/etc/passwall" ]; then
							mkdir -p /usr/local/etc/passwall
						fi
						echo -n "$dnsConfig" >/usr/local/etc/passwall/dnsConfig.tmp
					fi
					if [ "$dnsConfig" != "127.0.0.1#$dnsPort" ]; then
						uci delete dhcp.@dnsmasq[0].server
						uci add_list dhcp.@dnsmasq[0].server=127.0.0.1#$dnsPort
						uci commit dhcp
						/etc/init.d/dnsmasq restart
					fi
					iptables -t mangle -A passwallIPV4 -d $ipv4 -j RETURN
				else
					iptables -t mangle -A passwallIPV4 -d $ipv4 -p tcp -j RETURN
					iptables -t mangle -A passwallIPV4 -d $ipv4 -p udp ! --dport 53 -j RETURN
				fi
			else
				iptables -t mangle -A passwallIPV4 -d $ipv4 -j RETURN
			fi
		done
		# 来自公网ipv4地址的流量不走代理
		for ipv4 in $publicIPV4; do
			if [ ! -z "$fakeIPV4" ]; then
				iptables -t mangle -A passwallIPV4 -s $ipv4 ! -d $fakeIPV4 -j RETURN
			else
				iptables -t mangle -A passwallIPV4 -s $ipv4 -j RETURN
			fi
		done
		# 目标为其他IPV4保留网段的流量不走代理
		iptables -t mangle -A passwallIPV4 -d 0.0.0.0/8 -j RETURN
		iptables -t mangle -A passwallIPV4 -d 224.0.0.0/4 -j RETURN
		iptables -t mangle -A passwallIPV4 -d 127.0.0.1/32 -j RETURN
		iptables -t mangle -A passwallIPV4 -d 255.255.255.255/32 -j RETURN

		# 设备白名单不走代理
		while IFS= read -r line; do
			line=$(echo "$line" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
			case "$line" in
			??:??:??:??:??:??)
				iptables -t mangle -A passwallIPV4 -m mac --mac-source "$line" -j RETURN
				;;
			esac
		done </usr/local/etc/passwall/rules/局域网设备白名单.txt
		# 处理过的流量打上标记，避免循环
		if [ ! -z "$passwallMark" ]; then
			iptables -t mangle -A passwallIPV4 -j RETURN -m mark --mark $passwallMark
		fi
		iptables -t mangle -A passwallIPV4 -p udp -j TPROXY --on-ip 127.0.0.1 --on-port $tproxyPort --tproxy-mark 1
		iptables -t mangle -A passwallIPV4 -p tcp -j TPROXY --on-ip 127.0.0.1 --on-port $tproxyPort --tproxy-mark 1
		iptables -t mangle -A PREROUTING -j passwallIPV4

		# 本机IPV4设置
		iptables -t mangle -N passwallIPV4MASK
		# 放行代理端口
		if [ -n "$proxyPorts" ]; then
			for port in $proxyPorts; do
				port=$(echo "$port" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
				iptables -t mangle -A passwallIPV4MASK -p tcp --dport $port -j RETURN
				iptables -t mangle -A passwallIPV4MASK -p udp --dport $port -j RETURN
			done
		fi
		# 目标为本机IPV4网段的流量不走代理
		lanIP=$(echo $lanIPV4 | cut -d'/' -f1)
		iptables -t mangle -A passwallIPV4MASK -d $lanIP -j RETURN
		for ipv4 in $localIPV4; do
			if [ $ipv4 == $lanIPV4 ]; then
				# 判断是否自定义了dns接口
				if cat /usr/local/etc/passwall/config.json | jq -e '.inbounds | any(.type == "direct")' >/dev/null; then
					iptables -t mangle -A passwallIPV4MASK -d $ipv4 -j RETURN
				else
					iptables -t mangle -A passwallIPV4MASK -d $ipv4 -p tcp -j RETURN
					iptables -t mangle -A passwallIPV4MASK -d $ipv4 -p udp ! --dport 53 -j RETURN
				fi
			else
				iptables -t mangle -A passwallIPV4MASK -d $ipv4 -j RETURN
			fi
		done
		# 来自公网ipv4地址的流量不走代理
		for ipv4 in $publicIPV4; do
			if [ ! -z "$fakeIPV4" ]; then
				iptables -t mangle -A passwallIPV4MASK -s $ipv4 ! -d $fakeIPV4 -j RETURN
			else
				iptables -t mangle -A passwallIPV4MASK -s $ipv4 -j RETURN
			fi
		done

		# 目标为其他IPV4保留网段的流量不走代理
		iptables -t mangle -A passwallIPV4MASK -d 0.0.0.0/8 -j RETURN
		iptables -t mangle -A passwallIPV4MASK -d 224.0.0.0/4 -j RETURN
		iptables -t mangle -A passwallIPV4MASK -d 127.0.0.0/8 -j RETURN
		iptables -t mangle -A passwallIPV4MASK -d 255.255.255.255/32 -j RETURN

		# 处理过的流量打上标记，避免循环
		if [ ! -z "$passwallMark" ]; then
			iptables -t mangle -A passwallIPV4MASK -j RETURN -m mark --mark $passwallMark
		fi
		iptables -t mangle -A passwallIPV4MASK -p udp -j MARK --set-mark 1
		iptables -t mangle -A passwallIPV4MASK -p tcp -j MARK --set-mark 1
		iptables -t mangle -A OUTPUT -j passwallIPV4MASK

#		iptables -t mangle -N diverIPV4
#		iptables -t mangle -A diverIPV4 -j MARK --set-mark 1
#		iptables -t mangle -A diverIPV4 -j ACCEPT
#		iptables -t mangle -I PREROUTING -p tcp -m socket -j diverIPV4
		# 判断主机是否支持IPV6
		if command -v ip6tables >/dev/null 2>&1; then
			echo "/etc/init.d/passwall restart" >> /lib/netifd/ppp6-up
			# 获取本机IPV6网段
			localIPV6=$(ip -6 -o -f inet6 addr show | awk '/scope/ {print $4}')
			publicIPV6=$(ip -6 -o -f inet6 addr show | grep "br-lan" | grep "scope global dynamic noprefixroute" | awk '/scope/ {print $4}' | cut -d'/' -f1)
			# 新建路由表
			ip -6 route add local default dev lo table 106
			ip -6 rule add fwmark 1 table 106 priority 1024
			# 局域网IPV6设置
			ip6tables -t mangle -N passwallIPV6
			# 放行代理端口
			if [ -n "$proxyPorts" ]; then
				for port in $proxyPorts; do
					port=$(echo "$port" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
					ip6tables -t mangle -A passwallIPV6 -p tcp --dport $port -j RETURN
					ip6tables -t mangle -A passwallIPV6 -p udp --dport $port -j RETURN
				done
			fi
			# 目标为本机IPV6网段的流量不走代理
			for ipv6 in $localIPV6; do
				ip6tables -t mangle -A passwallIPV6 -d $ipv6 -j RETURN
			done
			# 来自公网ipv6的流量不走代理
			for ipv6 in $publicIPV6; do
				if [ ! -z "$fakeIPV6" ]; then
					ip6tables -t mangle -A passwallIPV6 -s $ipv6 ! -d $fakeIPV6 -j RETURN
				else
					ip6tables -t mangle -A passwallIPV6 -s $ipv6 -j RETURN
				fi
			done
			# 设备白名单不走代理
			while IFS= read -r line; do
				line=$(echo "$line" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
				case "$line" in
				??:??:??:??:??:??)
					ip6tables -t mangle -A passwallIPV6 -m mac --mac-source "$line" -j RETURN
					;;
				esac
			done </usr/local/etc/passwall/rules/局域网设备白名单.txt
			# 处理过的流量打上标记，避免循环
			if [ ! -z "$passwallMark" ]; then
				ip6tables -t mangle -A passwallIPV6 -j RETURN -m mark --mark $passwallMark
			fi
			ip6tables -t mangle -A passwallIPV6 -p udp -j TPROXY --on-ip ::1 --on-port $tproxyPort --tproxy-mark 1
			ip6tables -t mangle -A passwallIPV6 -p tcp -j TPROXY --on-ip ::1 --on-port $tproxyPort --tproxy-mark 1
			ip6tables -t mangle -A PREROUTING -j passwallIPV6

			# 本机IPV6设置
			ip6tables -t mangle -N passwallIPV6MASK
			# 放行代理端口
			if [ -n "$proxyPorts" ]; then
				for port in $proxyPorts; do
					port=$(echo "$port" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
					ip6tables -t mangle -A passwallIPV6MASK -p tcp --dport $port -j RETURN
					ip6tables -t mangle -A passwallIPV6MASK -p udp --dport $port -j RETURN
				done
			fi
			# 目标为本机IPV6网段的流量不走代理
			for ipv6 in $localIPV6; do
				ip6tables -t mangle -A passwallIPV6MASK -d $ipv6 -j RETURN
			done
			# 来自公网ipv6的流量不走代理
			for ipv6 in $publicIPV6; do
				if [ ! -z "$fakeIPV6" ]; then
					ip6tables -t mangle -A passwallIPV6MASK -s $ipv6 ! -d $fakeIPV6 -j RETURN
				else
					ip6tables -t mangle -A passwallIPV6MASK -s $ipv6 -j RETURN
				fi
			done
			# 处理过的流量打上标记，避免循环
			if [ ! -z "$passwallMark" ]; then
				ip6tables -t mangle -A passwallIPV6MASK -j RETURN -m mark --mark $passwallMark
			fi
			ip6tables -t mangle -A passwallIPV6MASK -p udp -j MARK --set-mark 1
			ip6tables -t mangle -A passwallIPV6MASK -p tcp -j MARK --set-mark 1
			ip6tables -t mangle -A OUTPUT -j passwallIPV6MASK

#			ip6tables -t mangle -N diverIPV6
#			ip6tables -t mangle -A diverIPV6 -j MARK --set-mark 1
#			ip6tables -t mangle -A diverIPV6 -j ACCEPT
#			ip6tables -t mangle -I PREROUTING -p tcp -m socket -j diverIPV6
		fi

	elif cat /usr/local/etc/passwall/config.json | jq -e '.inbounds | any(.type == "tun")' >/dev/null; then
		rm -f /etc/config/network.bak
		cp /etc/config/network /etc/config/network.bak
		rm -f /etc/config/firewall.bak
		cp /etc/config/firewall /etc/config/firewall.bak
		# 添加防火墙规则
		cat <<EOF >>/etc/config/firewall
config zone
        option name 'proxy'
        option forward 'REJECT'
        option output 'ACCEPT'
        option input 'ACCEPT'
        option mtu_fix '1'
        option device 'tun0'
        list network 'proxy'

config forwarding
        option name 'lan-proxy'
        option dest 'proxy'
        option src 'lan'
EOF
		# 添加网口
		cat <<EOF >>/etc/config/network
config interface 'proxy'
        option proto 'none'
        option device 'tun0'
EOF
		# 添加iptables命令
		iptables -I FORWARD -o tun+ -j ACCEPT
	else
		exit 1
	fi
}
